name: url-shortner-ci

on:
  push:
    paths:
      - "Url-Shortner/**"
      - ".github/workflows/url_shortner_ci.yml"

  pull_request:
    paths:
      - "Url-Shortner/**"
      - ".github/workflows/url_shortner_ci.yml"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ruff
        run: pip install ruff

      - name: Run Linter
        run: ruff check Url-Shortner/backend