name: url-shortner-ci

on:
  push:
    paths:
      - "Url-Shortner/**"
      - ".github/workflows/url_shortner_ci.yml"

  pull_request:
    paths:
      - "Url-Shortner/**"
      - ".github/workflows/url_shortner_ci.yml"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Pyhton
        uses: actions/setup-python@v5
        with:
          pyhton-version: "3.12"

      - name: install backend dependencies
        run: pip install -r Url-Shortner/backend/requirements.txt

      - name: install development dependencies
        run: pip install -r Url-Shortner/backend/requirements-dev.txt

      - name: Run Linter
        run: ruff check Url-Shortner/backend

      - name: Run tests
        run: python -m pytest Url-Shortner/backend/tests